import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage<{ onClick(): void }> = ({ onClick }) => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <h1 className="text-3xl font-bold underline">
          Welcome to <a onClick={onClick}>Next.js!</a>
        </h1>

      </main>
    </div>
  );
};

export default Home;
